name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release type - major, minor or patch"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major
      additionalFlags:
        description: "Additional flags for pre-releases, e.g. '--dry-run', '--preRelease=beta' or '--preRelease'"
        required: false
        type: string

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Package
        run: yarn build
        env:
          NODE_ENV: production
      - name: Run tests
        run: npm test
      - name: Upload built package
        uses: actions/upload-artifact@v2
        with:
          name: compiled-package
          path: dist/

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node version
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Setup Git
        run: |
          git config --global user.name "stateful-wombot"
          git config --global user.email "christian+github-bot@stateful.com"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Download built package
        uses: actions/download-artifact@v2
        with:
          name: compiled-package
          path: dist/
      - name: Release
        run: npm run release:ci -- ${{github.event.inputs.releaseType}} ${{github.event.inputs.additionalFlags}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
